version: '3'

services:
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    tty: true
  node:
    image: node:14.15
    command: bash -c "npm start"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    tty: true